export { default as LoginRoute } from './LoginRoute'
export { default as ViewDealsRoute } from './ViewDealsRoute'
export { default as SignUpRoute } from './SignUpRoute'
export { default as ShoppingCartRoute } from './ShoppingCartRoute'
export { default as ProfileRoute } from './ProfileRoute'
export { default as HistoryRoute } from './HistoryRoute'
